-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 19:58:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `idalunos` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `cpf` CHAR(11) NULL,
  `telefone` CHAR(12) NULL,
  `e-mail` VARCHAR(30) NULL,
  `data_nasc` DATE NULL,
  PRIMARY KEY (`idalunos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `requisito` VARCHAR(50) NULL,
  PRIMARY KEY (`idcursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `idturmas` INT NOT NULL,
  `instrutores` VARCHAR(30) NULL,
  `data_inicio` DATE NULL,
  `data_final` DATE NULL,
  `carga_horaria` SMALLINT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_cursos` (
  `alunos_idalunos` INT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`alunos_idalunos`, `cursos_idcursos`),
  INDEX `fk_alunos_has_cursos_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  INDEX `fk_alunos_has_cursos_alunos_idx` (`alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_cursos_alunos`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `mydb`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_cursos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_turmas` (
  `cursos_idcursos` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`cursos_idcursos`, `turmas_idturmas`),
  INDEX `fk_cursos_has_turmas_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_cursos_has_turmas_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_turmas_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `mydb`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_turmas` (
  `alunos_idalunos` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`alunos_idalunos`, `turmas_idturmas`),
  INDEX `fk_alunos_has_turmas_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_alunos_has_turmas_alunos1_idx` (`alunos_idalunos` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_turmas_alunos1`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `mydb`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `mydb`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutores` (
  `id_instrutor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `valor_hora` VARCHAR(45) NULL,
  `certificados` VARCHAR(45) NULL,
  PRIMARY KEY (`id_instrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutores_has_turmas` (
  `instrutores_id_instrutor` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`instrutores_id_instrutor`, `turmas_idturmas`),
  INDEX `fk_instrutores_has_turmas_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_instrutores_has_turmas_instrutores1_idx` (`instrutores_id_instrutor` ASC) VISIBLE,
  CONSTRAINT `fk_instrutores_has_turmas_instrutores1`
    FOREIGN KEY (`instrutores_id_instrutor`)
    REFERENCES `mydb`.`instrutores` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `mydb`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutores_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutores_has_cursos` (
  `instrutores_id_instrutor` INT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`instrutores_id_instrutor`, `cursos_idcursos`),
  INDEX `fk_instrutores_has_cursos_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  INDEX `fk_instrutores_has_cursos_instrutores1_idx` (`instrutores_id_instrutor` ASC) VISIBLE,
  CONSTRAINT `fk_instrutores_has_cursos_instrutores1`
    FOREIGN KEY (`instrutores_id_instrutor`)
    REFERENCES `mydb`.`instrutores` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutores_has_cursos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
